VCS path curations for AWS SDK for .NET
oss-review-toolkit/ort-config pull request #123
Opened 2023-04-24 12:46 UTC by MarcelBochtler

2023-04-24 14:25 UTC, MarcelBochtler commented
The version ranges generated by the task are not seen as valid, because Semver4j doesn't support the four Digit version numbers used by the AWS SDK for .NET.

How should I handle this? Make the version range valid by removing the trailing `.0` from the version ranges?

2023-04-25 08:46 UTC, mnonnenmacher commented
> How should I handle this? Make the version range valid by removing the trailing `.0` from the version ranges?

This is an option, but you would have to verify that the four digit versions are matched by the curations.

2023-04-25 08:58 UTC, MarcelBochtler commented
> > How should I handle this? Make the version range valid by removing the trailing `.0` from the version ranges?
> 
> This is an option, but you would have to verify that the four digit versions are matched by the curations.

Added a test for this: https://github.com/oss-review-toolkit/ort/pull/6922

2023-04-25 10:43 UTC, MarcelBochtler commented
> Do we need this code for generating the curations in future?

Yes, for new packages created in this monorepo, this code can be reused.
Additionally, the version ranges might be adjusted if this curation is no longer valid for the open range which is currently used everywhere:
https://github.com/oss-review-toolkit/ort-config/blob/be2fd8918715b852cde26877fb55a6fbac5132dc/tools/curations/buildSrc/src/main/kotlin/Utils.kt#L44-L48

2023-04-26 06:24 UTC, mnonnenmacher requested changes

2023-04-26 06:24 UTC, mnonnenmacher commented on tools/curations/buildSrc/src/main/kotlin/GenerateAwsSdkForNetCurationsTask.kt
> +                        val threeDigitVersionTag = tag.removeSuffix(".0")
Sometimes it's also ".1", so probably better like this: `if( tag.count { it == '.' } == 3) tag.substringBeforeLast(".") else tag`

2023-04-26 13:15 UTC, mnonnenmacher approved these changes

2023-04-26 14:41 UTC, merged