chore: Add PyPI::mock curation to all versions
oss-review-toolkit/ort-config pull request #150
Opened 2023-12-11 12:03 UTC by brunopacheco1

OSS Review Toolkit did not find a license for `PyPI::mock`. Checking out the repo it is licensed under BSD-2-Clause since 10 years ago.

2023-12-11 14:11 UTC, sschuberth commented
@brunopacheco1 please have a look at the failed verification check: In order to not fall into the trap of giving legal advice, curations in this repository must not directly contain concluded licenses. Generally, explicitly concluding licenses via curations is a "sledge hammer" method as it causes all declared and detected license information to be ignored, and it is completely nontransparent how the conclusion was achieved.

Thus, we unfortunately cannot accept the contribution as-is.

2023-12-11 22:39 UTC, brunopacheco1 commented
@sschuberth True, it was a mistake on my side. The PR is fixed.

2023-12-12 06:56 UTC, sschuberth requested changes

2023-12-12 06:56 UTC, sschuberth commented on curations/PyPI/_/mock.yml
> +      "BSD License": "BSD-2-Clause"
Your curation IMO does not really match what you're saying in the commit message:

> OSS Review Toolkit did not find a license for `PyPI::mock`.

If the ORT analyzer wouldn't have been able to find [the declared license](https://github.com/testing-cabal/mock/blob/d344fa2794b3b1ae7e4a4dbf265fb040d6f41d1f/setup.cfg#L12) there would be no point in mapping it.

So actually, I believe what you want to say is:

> The package's metadata data only declares an unspecific "BSD License", but a closer look at the `LICENSE.txt` reveals that concretely always the "BSD-2-Clause" license has been used.

2023-12-12 12:08 UTC, brunopacheco1 commented on curations/PyPI/_/mock.yml
> +      "BSD License": "BSD-2-Clause"
Indeed your suggestion is more appropriate, I will update comment and commit message.

 Regarding the version, is it advisable to add version always? Or can we have exceptions? This case the license has not changed yet.

2023-12-12 14:32 UTC, sschuberth commented on curations/PyPI/_/mock.yml
> +      "BSD License": "BSD-2-Clause"
Regarding the version, it's advisable to at least add an upper bound of the current version, since we cannot foresee if the future the license would change.

2023-12-12 19:11 UTC, brunopacheco1 commented on curations/PyPI/_/mock.yml
> +      "BSD License": "BSD-2-Clause"
Changes done accordingly.

2023-12-12 21:15 UTC, sschuberth approved these changes

2023-12-12 21:15 UTC, merged