chore: Add a VCS / path curation for `flexmark-util`
oss-review-toolkit/ort-config pull request #154
Opened 2023-12-14 18:13 UTC by sschuberth

2023-12-15 08:13 UTC, fviernau requested changes

2023-12-15 08:13 UTC, fviernau commented on curations/Maven/com.vladsch.flexmark/flexmark-util.yml
> +      No sources artifact published and no <scm> tag in POM. Repository found via Internet search.
Would it make sense to drop "No sources artifact published" as irrelevant? Maybe also "Repository found via Internet search." ?

idea: we could align on "The package metadata lacks the VCS info." ?

2023-12-15 08:19 UTC, sschuberth commented on curations/Maven/com.vladsch.flexmark/flexmark-util.yml
> +      No sources artifact published and no <scm> tag in POM. Repository found via Internet search.
I've reused the wording from the existing https://github.com/oss-review-toolkit/ort-config/blob/main/curations/Maven/com.vladsch.flexmark/flexmark-all.yml which I wanted to align with.

I believe it's not irrelevant that no sources artifact is published, otherwise the question could arise why it's not being used. This makes more clear that fixing the VCS info is our only option, even for users that have configured ORT to prefer source artifacts over VCS locations.

So, whatever wording change we eventually do in the end, it should be applied to `flexmark-all`, too.

2023-12-18 11:14 UTC, sschuberth commented on curations/Maven/com.vladsch.flexmark/flexmark-util.yml
> +      No sources artifact published and no <scm> tag in POM. Repository found via Internet search.
> Would it make sense to drop "No sources artifact published" as irrelevant? Maybe also "Repository found via Internet search." ?

After our discussion, I've dropped the first sentence but kept the second, as to me it's important to explain *how* a conclusion / curation was achieved. That would be unclear when just stating "The package metadata lacks the VCS info".

2023-12-18 17:29 UTC, fviernau approved these changes

2023-12-18 17:29 UTC, merged