fix(antlr): Map "BSD License" to `ANTLR-PD` for version 2.7.7
oss-review-toolkit/ort-config pull request #160
Opened 2023-12-21 08:54 UTC by sschuberth

Version 2.7.7 declares "BSD License" in its POM [1], which is wrong when looking at the `LICENSE.txt` contained in the source artifact. Instead, it is the ANTLR-specific Public Domain license, see [2]

[1]: https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.pom
[2]: https://spdx.org/licenses/ANTLR-PD.html

2023-12-21 11:28 UTC, sschuberth commented
FYI @willebra.

2023-12-23 22:12 UTC, mnonnenmacher requested changes

2023-12-23 22:12 UTC, mnonnenmacher commented on curations/Maven/antlr/antlr.yml
> +      BSD License: "ANTLR-PD"
The explanation from the commit message should also be in the comment, as this is what will be contained in the ORT results and shown in reports. This is also a good candidate to make separate curations for the license mapping and the source artifact (as recently discussed in the core dev meeting) as they need different explanations.

2023-12-24 11:57 UTC, mnonnenmacher approved these changes

2023-12-24 11:57 UTC, merged