package-configurations: Add various PyPI packages
oss-review-toolkit/ort-config pull request #17
Opened 2022-03-11 21:36 UTC by tsteenbe

2022-04-05 08:25 UTC, fviernau requested changes

2022-04-05 08:25 UTC, fviernau commented on package-configurations/PyPI/_/flask/1.1.2/source-artifact.yml
> +  - pattern: "Flask-1.1.1/docs/**"
Is 1.1.1 in "Flask-1.1.1" correct?

2022-05-04 11:08 UTC, mnonnenmacher requested changes

2022-05-04 11:08 UTC, mnonnenmacher commented on package-configurations/PyPI/_/numpy/1.20.3/source-artifact.yml
> +    comment: "Match in related work section on '`VOLK`_ is a GPL3 library'."
Line breaks are missing at the end of this and several other files.

2022-06-20 07:57 UTC, tsteenbe commented on package-configurations/PyPI/_/flask/1.1.2/source-artifact.yml
> +  - pattern: "Flask-1.1.1/docs/**"
No, fixed it up

2022-06-21 10:39 UTC, mnonnenmacher approved these changes

2022-06-21 11:18 UTC, merged