feat(package-configurations): Add some path excludes for commons-compress
oss-review-toolkit/ort-config pull request #192
Opened 2024-05-28 17:44 UTC by sschuberth

First and foremost, exclude `some-900kb-text.txt` [1] which just contains random text in a single line, which makes ScanCode time out.

Secondly, while at it, also exclude the `.github` build directory committed to VCS.

[1]: https://github.com/apache/commons-compress/blob/rel/commons-compress-1.26.2/src/test/resources/org/apache/commons/compress/COMPRESS-649/some-900kb-text.txt

2024-05-28 18:52 UTC, tsteenbe requested changes
I also package configuration for this package that is pending us agree on some rules. Mine is a bit more elaborate

```
---
id: "Maven:org.apache.commons:commons-compress:1.26.2"
vcs:
  type: "Git"
  url: "https://gitbox.apache.org/repos/asf/commons-compress.git"
  revision: "95727006cac0892c654951c4e7f1db142462f22a"
path_excludes:
- pattern: ".github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "CODE_OF_CONDUCT.md"
  reason: "DOCUMENTATION_OF"
- pattern: "CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "SECURITY.md"
  reason: "DOCUMENTATION_OF"
- pattern: "src/changes/**"
  reason: "DOCUMENTATION_OF"
- pattern: "src/main/java/org/apache/commons/compress/archivers/examples/**"
  reason: "DOCUMENTATION_OF"
- pattern: "src/site/**"
  reason: "DOCUMENTATION_OF"
- pattern: "src/test/**"
  reason: "TEST_OF"
license_finding_curations:
- path: "src/main/java/org/apache/commons/compress/archivers/zip/*.java"
  detected_license: "LicenseRef-scancode-proprietary-license"
  reason: "REFERENCE"
  comment: |
    Match on 'Refer to the section in this document entitled Incorporating PKWARE Proprietary Technology 
    into Your Product" for more information', see
    https://github.com/apache/commons-compress/blob/rel/commons-compress-1.26.2/src/main/java/org/apache/commons/compress/archivers/zip/X0017_StrongEncryptionHeader.java#L251-L252
    Git blame on sentence so this is a reference to ZIP file format specification, see
    https://github.com/apache/commons-compress/commit/a433f62
  concluded_license: "NONE"
```

2024-05-28 18:57 UTC, sschuberth commented
> I also package configuration for this package that is pending us agree on some rules. Mine is a bit more elaborate

IMO that's not a reason to block this PR, though. I'm sorry, but we cannot hold our breath and wait for you to move things forward, see also https://github.com/oss-review-toolkit/ort-config/pull/131 which has been pending for almost a year.

And most importantly, your version lacks the path exclude for the file that causes the ScanCode timeout. Thus I'd like to get this merged, and later add your changes to it.

2024-05-29 06:39 UTC, fviernau requested changes

2024-05-29 06:39 UTC, fviernau commented on package-configurations/Maven/org.apache.commons/commons-compress/1.26.2/vcs.yml
> +  - pattern: "src/test/resources/org/apache/commons/compress/COMPRESS-649/some-900kb-text.txt"
This should be just `src/test/**`.

2024-05-29 08:11 UTC, tsteenbe commented
> IMO that's not a reason to block this PR, though. I'm sorry, but we cannot hold our breath and wait for you to move things forward, see also #131 which has been pending for almost a year.

Did I say I wan't to block this PR - maybe it wasn't clear from my comment but I simply requested this PR to be update to my version

2024-05-29 16:01 UTC, sschuberth commented
> Did I say I wan't to block this PR - maybe it wasn't clear from my comment but I simply requested this PR to be updated to include the additional line from the codeblock in my comment

Then this was indeed a misunderstanding. I've reviewed and incorporated your changes.

2024-05-29 20:50 UTC, tsteenbe approved these changes

2024-05-30 04:48 UTC, merged