feat(curations): Add a VCS curation for XMLUnit < 2.0
oss-review-toolkit/ort-config pull request #194
Opened 2024-06-06 15:18 UTC by sschuberth

Note that XMLUnit 2.x is hosted at [1].

[1]: https://github.com/xmlunit/xmlunit

2024-06-06 16:11 UTC, fviernau requested changes

2024-06-06 16:11 UTC, fviernau commented on curations/Maven/xmlunit/xmlunit.yml
> +- id: "Maven:xmlunit:xmlunit:(,2.0["
commit message: How about the following title? 

feat(curations): Set the VCS info for `xmlunit`

2024-06-06 16:11 UTC, fviernau commented on curations/Maven/xmlunit/xmlunit.yml
> +    declared_license_mapping:
Same here:

feat(curations): Map a declared license for `xmlunit`

2024-06-06 16:50 UTC, sschuberth commented on curations/Maven/xmlunit/xmlunit.yml
> +- id: "Maven:xmlunit:xmlunit:(,2.0["
I'd like to emphasize it's for versions < 2 only, as 2.x versions do not have these issues anymore.

2024-06-06 16:51 UTC, sschuberth commented on curations/Maven/xmlunit/xmlunit.yml
> +    declared_license_mapping:
I basically have no objections, but I'd just like to understand: How is that message better than mine?

2024-06-06 20:20 UTC, fviernau commented on curations/Maven/xmlunit/xmlunit.yml
> +    declared_license_mapping:
For the bottom commit "curation(s)" is not mentioned twice...less redundant.
The proposed way is a bit shorter and focus a tad more on describing the effect on the curation, not so much the property used for it.

2024-06-06 20:20 UTC, fviernau approved these changes

2024-06-07 05:58 UTC, sschuberth commented on curations/Maven/xmlunit/xmlunit.yml
> +    declared_license_mapping:
I see, thanks for explaining. I made the messages a bit more compact.

2024-06-07 05:58 UTC, merged