feat(custom-license-texts): Add "SAP Developer License Agreement" content
oss-review-toolkit/ort-config pull request #201
Opened 2024-06-18 09:22 UTC by xLexip

* Source: https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt

Signed-off-by: xLexip <x@lexip.dev>

2024-06-18 09:38 UTC, sschuberth commented
For reference, I just verified that ScanCode does not detect this license directly, but as

    "LicenseRef-scancode-nilsson-historical AND LicenseRef-scancode-unknown-license-reference AND LicenseRef-scancode-other-permissive"

so having a custom `LicenseRef` for it seems sensible.

However, I wonder whether by convention we should use "ort" (not "SAP") as the "namespace", i.e. the part after the `LicenseRef-` prefix.

2024-06-18 09:49 UTC, tsteenbe commented
Since the ORT project will be assigning the LicenseRef to this license it needs to be in our namespace so imo it should start with `LicenseRef-ort` -  `LicenseRef-SAP-*` may be used by SAP itself which may result in a license namespace conflict.

2024-06-18 09:52 UTC, sschuberth commented
> `LicenseRef-SAP-*` may be used by SAP itself which may result in a license namespace conflict.

I Agree.

@xLexip please rename the file to `LicenseRef-ort-SAP-Developer-License-Agreement`, amending your existing commit.

2024-06-18 09:54 UTC, xLexip commented
Alright, done @sschuberth.

2024-06-18 10:01 UTC, fviernau requested changes

2024-06-18 10:01 UTC, fviernau commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement
> +SAP DEVELOPER LICENSE AGREEMENT
As there seem to be multiple versions, shall we make the version part of the identifier?

2024-06-18 10:03 UTC, fviernau commented
What's the rationale @oss-review-toolkit/core-devs to start adding custom license texts into this repository? 
Alternatively, the text could be contributed to ScanCode.

2024-06-18 10:05 UTC, tsteenbe commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement
> +SAP DEVELOPER LICENSE AGREEMENT
You are right, quick google and I found https://tools.hana.ondemand.com/developer-license-3_2.txt so the correct way per SPDX to encode this license would be LicenseRef-ort-SAP-Developer-License-Agreement-3.1

2024-06-18 10:05 UTC, sschuberth commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement
> +SAP DEVELOPER LICENSE AGREEMENT
Good point, we should indeed add a "-3.1" suffix (IMO less preferably "-3_1" or "-3-1") to the file name.

2024-06-18 10:08 UTC, sschuberth commented
> What's the rationale @oss-review-toolkit/core-devs to start adding custom license texts into this repository?

Users who make use of this repo can then curate license findings to this custom license and get a proper license text in reports.

> Alternatively, the text could be contributed to ScanCode.

That should be done additionally, not alternatively, as it does not help users until a new ScanCode version with the additional rule is released.

2024-06-18 10:11 UTC, fviernau commented
> Users who make use of this repo can then curate license findings to this custom license and get a proper license text in reports.

> That should be done additionally, not alternatively, as it does not help users until a new ScanCode version with the additional rule is released.

This is a clear indication that the custom license text is a temporary solution. This was one of the main goals the custom license text feature was invented for. So, my underlying question has not been discussed: Why should we invest effort into temporary solutions instead of leaving this up to the users entirely?

2024-06-18 12:20 UTC, sschuberth commented
> To me this is a clear indication that the custom license text is a temporary solution.

Ideally yes, absolutely.

> Why should we invest effort into temporary solutions instead of leaving this up to the users entirely?

To not require our users to each do the same work (internally) again.

> to have the agreement that the license ID can be dropped again, once available in ScanCode

... *and* the ORT Docker image comes with the version of ScanCode that adds the license. That approach would make sense to me.

2024-06-20 06:07 UTC, xLexip commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement
> +SAP DEVELOPER LICENSE AGREEMENT
I have added both versions with the suffix "-3.x" accordingly, @sschuberth.

2024-06-20 06:50 UTC, fviernau submitted a review, later dismissed

2024-06-20 07:44 UTC, sschuberth requested changes

2024-06-20 07:44 UTC, sschuberth commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement-3.1
> +Source: https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt
This source line is not part of the original linked license text. I believe we should aim for only committing the exact 1:1 license text here. The origin should be documented as part of the commit message. Or what do @oss-review-toolkit/core-devs think?

2024-06-20 08:13 UTC, fviernau commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement-3.1
> +Source: https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt
good catch imo.

2024-06-20 09:20 UTC, xLexip commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement-3.1
> +Source: https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt
Removed them.

2024-06-20 09:38 UTC, sschuberth commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement-3.1
> +Source: https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt
@xLexip, I'm still seeing some whitespace / encoding related differences compared to the original files. Please really just take them as-is, without making any modifications compared to the upstream file. I'm expecting the 3.1. file to have a SHA1 sum of 65b2e7cba1e678ae1f0ca059ab42dff8d1a00777, and for 3.2 cbff7422c9b707e418665efeff42ec77e2f6fab7 respectively.

2024-06-20 09:52 UTC, xLexip commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement-3.1
> +Source: https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt
@sschuberth done....

2024-06-20 10:52 UTC, sschuberth commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement-3.1
> +Source: https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt
One more nit on the commit message: Why does it link to its own PR by adding "#201" to the commit message? I'd prefer to have that dropped.

2024-06-20 11:00 UTC, xLexip commented on custom-license-texts/LicenseRef-ort-SAP-Developer-License-Agreement-3.1
> +Source: https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt
To have a reference to this entire discussion in the history for the next person who wants to add license text and looks at the previous changes. Removed it.

2024-06-20 11:19 UTC, sschuberth approved these changes

2024-06-20 11:20 UTC, merged