Set the VCS revision for SharpSvn.1.9-x64 NuGet package
oss-review-toolkit/ort-config pull request #209
Opened 2024-07-09 11:37 UTC by haikoschol

FYI @sschuberth

2024-07-09 11:47 UTC, fviernau requested changes

2024-07-09 11:47 UTC, fviernau commented on curations/NuGet/_/SharpSvn.1.9-x64.yml
> +      listed as owner on https://www.nuget.org/packages/SharpSvn.1.9-x64.
I do not get how this first sentence relates to this curation.

2024-07-09 11:50 UTC, haikoschol commented on curations/NuGet/_/SharpSvn.1.9-x64.yml
> +      listed as owner on https://www.nuget.org/packages/SharpSvn.1.9-x64.
Maybe. It's meant to convey that I found the repo by googling "SharpSvn" instead of linked somewhere on https://www.nuget.org/packages/SharpSvn.1.9-x64.

2024-07-09 11:52 UTC, fviernau commented on curations/NuGet/_/SharpSvn.1.9-x64.yml
> +      listed as owner on https://www.nuget.org/packages/SharpSvn.1.9-x64.
Does ORT figure out the correct VCS URL? (If yes, I would suggest to remove the sentence)

2024-07-09 11:53 UTC, haikoschol commented on curations/NuGet/_/SharpSvn.1.9-x64.yml
> +      listed as owner on https://www.nuget.org/packages/SharpSvn.1.9-x64.
It does not and I need to add it. 🙏

2024-07-09 12:23 UTC, tsteenbe commented
The original maintainer of SharpSvn is @rhuijben and he his name is on https://github.com/AmpScm/SharpSvn/ so NuGet::SharpSvn.1.9-x64:1.9007.3987.251 was released on 19 Sept 2017 another potential VCS location maybe https://github.com/AmpScm/SharpSvn/tree/2d485aaca786ceb37078bf41667576a10e1efc89.

2024-07-09 14:43 UTC, fviernau submitted a review, later dismissed

2024-07-10 03:55 UTC, haikoschol commented on curations/NuGet/_/SharpSvn.1.9-x64.yml
> +      revision: "2d485aaca786ceb37078bf41667576a10e1efc89"
What should the version range be?

2024-07-10 05:07 UTC, fviernau commented on curations/NuGet/_/SharpSvn.1.9-x64.yml
> +      revision: "2d485aaca786ceb37078bf41667576a10e1efc89"
Just noticed that ranges do not work for these versions. But, as the 1.9 is part of the name, IMO it would be ok to omit the version entirely instead.

2024-07-10 08:16 UTC, haikoschol commented on curations/NuGet/_/SharpSvn.1.9-x64.yml
> +      Tag missing in Git, revision found by correlating commits with package release date.
No idea how I ended up with that. Did this before coffee... Anyway, it's a single commit now.

2024-07-10 08:24 UTC, sschuberth approved these changes

2024-07-10 08:25 UTC, merged