Several NuGet curations
oss-review-toolkit/ort-config pull request #224
Opened 2024-07-29 07:46 UTC by fviernau

2024-07-29 08:36 UTC, fviernau commented on curations/NuGet/Microsoft.Net/Http.Headers.yml
> -- id: "NuGet:Microsoft.Net:Http.Headers:[2.1.7,)"
The syntax is documented here: https://ant.apache.org/ivy/history/2.1.0/settings/version-matchers.html

Yes, the previous curation was wrong.

2024-07-29 08:37 UTC, fviernau commented on curations/NuGet/Microsoft.AspNetCore/Hosting.Abstractions.yml
> -- id: "NuGet:Microsoft.AspNetCore:Hosting.Abstractions:[2.1.7,)"
Yes it was.

2024-07-29 08:44 UTC, haikoschol approved these changes

2024-07-29 10:21 UTC, haikoschol requested changes

2024-07-29 10:21 UTC, haikoschol commented on curations/NuGet/_/log4net.yml
> +    comment: "Multiple tags matching this version.""
There's a duplicate `"` at the end.

2024-07-29 10:21 UTC, haikoschol commented on curations/NuGet/_/log4net.yml
> +    comment: "Multiple tags matching this version.""
There's a duplicate `"` at the end.

2024-07-29 10:21 UTC, haikoschol commented on curations/NuGet/_/log4net.yml
> +    comment: "Multiple tags matching this version.""
There's a duplicate `"` at the end.

2024-07-29 10:21 UTC, haikoschol commented on curations/NuGet/_/log4net.yml
> +    comment: "Multiple tags matching this version.""
There's a duplicate `"` at the end.

2024-07-29 10:21 UTC, haikoschol commented on curations/NuGet/_/log4net.yml
> +    comment: "Multiple tags matching this version.""
There's a duplicate `"` at the end.

2024-07-29 10:21 UTC, haikoschol commented on curations/NuGet/_/log4net.yml
> +    comment: "Multiple tags matching this version.""
There's a duplicate `"` at the end.

2024-07-29 10:21 UTC, haikoschol commented on curations/NuGet/_/log4net.yml
> +    comment: "Multiple tags matching this version.""
There's a duplicate `"` at the end.

2024-07-29 10:36 UTC, haikoschol approved these changes

2024-07-29 12:36 UTC, haikoschol approved these changes

2024-08-01 15:04 UTC, fviernau commented
I've integrated the changes into https://github.com/oss-review-toolkit/ort-config/pull/225.

2024-08-01 15:04 UTC, closed without merging