Further NuGet curation fixes
oss-review-toolkit/ort-config pull request #225
Opened 2024-08-01 13:38 UTC by fviernau

2024-08-02 07:04 UTC, haikoschol approved these changes

2024-08-14 11:02 UTC, sschuberth requested changes

2024-08-14 11:02 UTC, sschuberth commented on curations/NuGet/Microsoft.AspNetCore/Authentication.Abstractions.yml
> +- id: "NuGet:Microsoft.AspNetCore:Authentication.Abstractions:[3.0.0,)"
Also here version ranges seem to be swapped. In general, I'd prefer to have lower versions listed first.

2024-08-27 06:37 UTC, fviernau commented on curations/NuGet/Microsoft.Net/Http.Headers.yml
> +- id: "NuGet:Microsoft.Net:Http.Headers:[3.0.0,)"
For 3.0.0 and above the path should be fine, see https://github.com/dotnet/aspnetcore/tree/v3.0.0/src/Http/Headers.

For below 3.0.0 releases come from different repo, see https://github.com/aspnet/HttpAbstractions/tree/2.2.0/src/Microsoft.Net.Http.Headers.

2024-08-27 06:41 UTC, fviernau commented on curations/NuGet/Microsoft.AspNetCore/Authentication.Abstractions.yml
> +- id: "NuGet:Microsoft.AspNetCore:Authentication.Abstractions:[3.0.0,)"
> Also here version ranges seem to be swapped.

I think it's correct for the same rationale as for your analog comment in this PR.

> In general, I'd prefer to have lower versions listed first.

Can this be fixed in a separate effort for ALL file in the code base, please?

2024-08-27 12:05 UTC, sschuberth commented on curations/NuGet/Microsoft.Net/Http.Headers.yml
> +- id: "NuGet:Microsoft.Net:Http.Headers:[3.0.0,)"
I'm still confused. The existing curation sets the path to "src/Http/Headers/src" for version 2.1.7 and higher. I'm assuming that curation to be correct, at least exactly for version 2.1.7. But your new curation sets the path to "src/Microsoft.Net.Http.Headers" for version 3.0.0 and lower, including version 2.1.7. So is the existing curation wrong for version 2.1.7?

2024-08-27 14:19 UTC, sschuberth commented on curations/NuGet/Microsoft.Net/Http.Headers.yml
> +- id: "NuGet:Microsoft.Net:Http.Headers:[3.0.0,)"
To double-check, I've looked at the following link which have the package information in the lower left:

- https://nuget.info/packages/Microsoft.Net.Http.Headers/2.1.1 (most recent release before 2.1.14, comes from https://github.com/aspnet/HttpAbstractions)
- https://nuget.info/packages/Microsoft.Net.Http.Headers/2.1.14 (comes from https://github.com/dotnet/aspnetcore)
- https://nuget.info/packages/Microsoft.Net.Http.Headers/2.2.0 (first non-preview release after 2.1.14, again comes from https://github.com/aspnet/HttpAbstractions)

So that curation now looks good to me as well.

2024-08-27 14:20 UTC, sschuberth commented on curations/NuGet/Microsoft.AspNetCore/Authentication.Abstractions.yml
> +- id: "NuGet:Microsoft.AspNetCore:Authentication.Abstractions:[3.0.0,)"
Ok, I guess we can address this as part of https://github.com/oss-review-toolkit/ort-config/issues/132 with proper automation.

2024-08-27 14:26 UTC, sschuberth requested changes
How about splitting you all pure formatting commits out to a separate PR until those version 2.1.7 path issues are sorted out for all affected packages?

2024-08-28 07:10 UTC, fviernau commented on curations/NuGet/Microsoft.AspNetCore/Authentication.yml
> +      path: "src/Microsoft.AspNetCore.Authentication"
I don't see any problem here https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.

2024-08-28 07:29 UTC, fviernau commented
> How about splitting you all pure formatting commits out to a separate PR until those version 2.1.7 path issues are sorted out for all affected packages?

I went through all curations and found 2 more "version 2.1.17 like" issue which I fixed. I believe the curations are fine now.

2024-08-28 08:57 UTC, sschuberth commented on curations/NuGet/Microsoft.AspNetCore/Authentication.yml
> +      path: "src/Microsoft.AspNetCore.Authentication"
Ok, I thought it's the same problem again as from a pure text-diff perspective of a reviewer the `path` curation for version 2.1.7 is now different than before. The commit message says "Several targeted versions do not exist", but I would have wished this to be more explicit and name the non-existing versions.

2024-08-28 08:58 UTC, merged