Tools: Move code to buildSrc
oss-review-toolkit/ort-config pull request #33
Opened 2022-05-02 22:00 UTC by mnonnenmacher

See the commit messages for details.

2022-05-03 06:33 UTC, sschuberth requested changes

2022-05-03 06:33 UTC, sschuberth commented on tools/curations/build.gradle.kts
>          mavenCentral()
Why is this still needed in here?

2022-05-03 06:33 UTC, sschuberth commented on tools/curations/build.gradle.kts
> +tasks.register("verifyPackageCurations", VerifyPackageCurationsTask::class)
More compact:

```
tasks {
    register<GenerateAspNetCoreCurationsTask>("generateAspNetCoreCurations")
    register<GenerateAzureSdkForNetCurationsTask>("generateAzureSdkForNetCurations")
    register<GenerateDotNetRuntimeCurationsTask>("generateDotNetRuntimeCurations")
    register<VerifyPackageCurationsTask>("verifyPackageCurations")
}
```

2022-05-03 06:33 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/AbstractGenerateCurationsTask.kt
> +        val client = OkHttpClient()
Ho about moving this to a class variable to share the `client` across functions?

2022-05-03 06:33 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/AbstractGenerateCurationsTask.kt
> +                .build()
You could also move this common code out to a prepared builder on the class level, and refine that builder here with the URL, like `githubRequest.newBuilder().url().build()`.

2022-05-03 20:45 UTC, mnonnenmacher commented on tools/curations/build.gradle.kts
>          mavenCentral()
It isn't.

2022-05-04 07:42 UTC, sschuberth commented on tools/curations/build.gradle.kts
> +tasks.register<GenerateAspNetCoreCurationsTask>("generateAspNetCoreCurations")
Just double checking, do you prefer to repeat `task.` instead of wrapping in `tasks {}`?

2022-05-04 07:42 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/AbstractGenerateCurationsTask.kt
> +        Request.Builder().header("Authorization", okhttp3.Credentials.basic(githubUsername, githubToken))
This could be moved to a property to avoid recreation on each function call. However, that requires to call `build()` here, and `newBuilder()` in the caller. Which then effectively is also something like doing this twice... your choice.

2022-05-04 07:42 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/AbstractGenerateCurationsTask.kt
> +        Request.Builder().header("Authorization", okhttp3.Credentials.basic(githubUsername, githubToken))
Also, maybe import `okhttp3.Credentials` instead of using a FQN.

2022-05-04 08:07 UTC, mnonnenmacher commented on tools/curations/buildSrc/src/main/kotlin/AbstractGenerateCurationsTask.kt
> +        Request.Builder().header("Authorization", okhttp3.Credentials.basic(githubUsername, githubToken))
> This could be moved to a property to avoid recreation on each function call. However, that requires to call `build()` here, and `newBuilder()` in the caller. Which then effectively is also something like doing this twice... your choice.

I'm not quite sure how you imagine this to look like, but if it's about a performance optimization to not create a new builder for each call I think it's irrelevant because these functions are not called often.

2022-05-04 09:29 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/AbstractGenerateCurationsTask.kt
> +        Request.Builder().header("Authorization", okhttp3.Credentials.basic(githubUsername, githubToken))
For reference, this could look like:

    private val gitHubRequest = Request.Builder()
        .header("Authorization", Credentials.basic(githubUsername, githubToken)).build()

And then on the call side:

    val request = gitHubRequest.newBuilder()
        .url("https://api.github.com/repos/$owner/$repository/git/trees/$ref?recursive=1")
        .build()

2022-05-04 09:31 UTC, sschuberth approved these changes

2022-05-04 09:31 UTC, merged