Improve example rules
oss-review-toolkit/ort-config pull request #39
Opened 2022-06-22 10:08 UTC by tsteenbe

Please see individual commits for details.

Note: This is only part 1 of improving the rules, will submit part 2 when this PR is merged.

2022-06-22 13:26 UTC, fviernau requested changes
I haven't reviewed all yet as it is quite large. I'll continue later on...

2022-06-22 13:26 UTC, fviernau commented on evaluator-rules/src/main/resources/example.rules.kts
> +         return "name of the artifact"
could be done in one line like:
```
"name of the artifact".takeIf { url.isNullOrBlank()url.isNullOrBlank() } ?: "${url.substringAfterLast("/")}"
```

2022-06-22 13:40 UTC, sschuberth commented on evaluator-rules/src/main/resources/example.rules.kts
> +                |${resolveViolationInDependencySourceCodeText(pkg, license)}
Just double-checking: It is correct to the the margin character `|` here, although the text returned by `resolveViolationInDependency*` already contains the margin character itself?

2022-06-22 16:49 UTC, tsteenbe commented on evaluator-rules/src/main/resources/example.rules.kts
> +                |${resolveViolationInDependencySourceCodeText(pkg, license)}
Fixed it to be a direct return, was left-over after I moved the text that was there into `resolveViolation` functions.

2022-06-23 12:47 UTC, fviernau commented on evaluator-rules/src/main/resources/example.rules.kts
> +    if (isLabeled("project", "oss-project")) {
it's not yet fixed. Forgot to push again?

2022-06-23 13:05 UTC, fviernau commented on evaluator-rules/src/main/resources/example.rules.kts
> +fun isVcsScanned(id: Identifier): Boolean =
Return true if and only if the [ortResult] contains a scan result for the VCS of the package denoted by [id].

2022-06-23 13:05 UTC, fviernau commented on evaluator-rules/src/main/resources/example.rules.kts
> +fun Identifier.toCoordinatesWithoutVersion() = "$type:$namespace:$name"
Return the coordinates without the version.

2022-06-23 13:07 UTC, fviernau commented on evaluator-rules/src/main/resources/example.rules.kts
> +        } else {
Please drop the `else` in line 240, 244 and 249 (but keep the code residing in the else blocks.

2022-06-23 13:08 UTC, fviernau commented on evaluator-rules/src/main/resources/example.rules.kts
> +    @Suppress("UNUSED_PARAMETER") severity: Severity
Please drop this unused parameter.

2022-06-23 13:09 UTC, fviernau commented on evaluator-rules/src/main/resources/example.rules.kts
> +        } else {
Please drop the else to reduce level of nesting.

Same in several functions below.

2022-06-24 08:29 UTC, tsteenbe commented on evaluator-rules/src/main/resources/example.rules.kts
> +        } else {
I actually deliberately did to make it easier for non-technical people such a maybe legal counsels understand the policy.

2022-06-24 10:11 UTC, tsteenbe commented on evaluator-rules/src/main/resources/example.rules.kts
> +        PolicyRules.OSS_PROJECT -> ossProjectRules()
One of the selling points of ORT is that one can use it for compliance and contribution processes which is why I included OSS_PROJECT rules. Still a bit under developed but in my follow up PRs I will add more meat.

2022-06-24 10:12 UTC, tsteenbe commented on evaluator-rules/src/main/resources/example.rules.kts
> +val ortScanIssueTrackerName = "FOSS JIRA"
Lots of potential ORT users use JIRA, included this to help them better understand how they could build a ORT + JIRA process.

2022-06-24 10:12 UTC, tsteenbe commented on evaluator-rules/src/main/resources/example.rules.kts
> +        } else {
Leaving it as in my follow up PR I will build on top of this.

2022-06-24 10:35 UTC, fviernau commented on evaluator-rules/src/main/resources/example.rules.kts
> +    // unhandledLicenseRule()
Left over from debugging?

2022-06-24 10:55 UTC, tsteenbe commented on evaluator-rules/src/main/resources/example.rules.kts
> +    // unhandledLicenseRule()
Yes, fixed it.

2022-06-24 10:57 UTC, fviernau approved these changes

2022-06-24 10:57 UTC, merged