package-configurations: Add various versions of async packages
oss-review-toolkit/ort-config pull request #47
Opened 2022-07-26 12:47 UTC by ShrutiDadoo

Signed-off-by: Shruti Dadoo <shruti.dadoo@here.com>

2022-07-26 13:43 UTC, fviernau submitted a review, later dismissed

2022-07-26 18:08 UTC, MarcelBochtler requested changes

2022-07-26 18:08 UTC, MarcelBochtler commented on package-configurations/NPM/async/3.2.1/vcs.yml
> +  reason: "TEST_OF"
Missing empty line at the end of the file.

2022-07-26 18:08 UTC, MarcelBochtler commented on package-configurations/NPM/async/3.2.2/vcs.yml
> +  reason: "TEST_OF"
Missing empty line at the end of the file.

2022-07-26 18:08 UTC, MarcelBochtler commented on package-configurations/NPM/async/3.2.3/vcs.yml
> +  reason: "TEST_OF"
Missing empty line at the end of the file.

2022-07-26 18:08 UTC, MarcelBochtler commented on package-configurations/NPM/async/3.2.4/vcs.yml
> +  reason: "TEST_OF"
Missing empty line at the end of the file.

2022-07-27 04:18 UTC, tsteenbe submitted a review, later dismissed

2022-07-27 06:38 UTC, fviernau approved these changes

2022-07-27 14:21 UTC, fviernau approved these changes

2022-07-27 14:57 UTC, merged