evaluator-rules: Improve the disclaimer a bit
oss-review-toolkit/ort-config pull request #70
Opened 2022-10-21 11:52 UTC by fviernau

Drop the copy pasted mention of "ORT examples", make the disclaimer a bit more prominent and avoid using the term example overall while still making clear that no legal recommendation is made. While at it wrap it at 80 chars.

2022-10-21 11:53 UTC, tsteenbe requested changes

2022-10-21 11:53 UTC, tsteenbe commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> + *             no recommendation in any way. It is recommended to consult     *
It is recommended -> It's recommended

2022-10-21 12:07 UTC, mnonnenmacher commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> + *             no recommendation in any way. It is recommended to consult     *
I think in formal texts "it is" is the better choice than using a contraction.

2022-10-21 13:38 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> + *             no recommendation in any way. It is recommended to consult     *
@tsteenbe ok with changing it back again?

2022-10-21 17:03 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> + *             no recommendation in any way. It is recommended to consult     *
Changed it anyway as it's minor.

2022-10-24 07:20 UTC, tsteenbe approved these changes

2022-10-24 07:20 UTC, merged