Evaluator rules improvements
oss-review-toolkit/ort-config pull request #73
Opened 2022-11-14 13:22 UTC by fviernau

See individual commits.

2022-11-14 13:38 UTC, sschuberth requested changes

2022-11-14 13:38 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +    // ort.yml rules:
Nit: Maybe quote like `"ort.yml"`.

2022-11-14 13:38 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +    // rules for dependencies:
Nit: Please start these sentences capitalized.

2022-11-14 13:38 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +fun RuleSet.vulnerabilityInDependencyRule() = packageRule("VULNERABILITY_IN_DEPENDENCY") {
From a rule-authoring perspective, the new name is a bit misleading as there's also a `dependencyRule`, but you're using a `packageRule`.

2022-11-14 13:38 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +val fileChecksEnabled = ortResult.hasLabel("file-checks-enabled")
IMO better name the label `enable-file-checks`. Or probably yet better, do not name the rule after how the checks are technically implemented, but after the use-case. Like `enable-prior-to-oss-rules` or so.

2022-11-14 13:43 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +fun RuleSet.vulnerabilityInDependencyRule() = packageRule("VULNERABILITY_IN_DEPENDENCY") {
Hm, are you saying I should keep the previous name? 
(I found the new one more consistent, as it targets dependencies)
Whether the rule is executed once per edge in the tree or once per dependency IMO is not reflected in any name.

2022-11-14 14:09 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +fun RuleSet.vulnerabilityInDependencyRule() = packageRule("VULNERABILITY_IN_DEPENDENCY") {
I'm myself unsure what to do here. In rules-context, the term "dependency" actually is a synonym for "package reference". I believe @mnonnenmacher chose "dependencyRule" instead of (the formally more correct) "packageReferenceRule" back then just because it's a simpler term, and we wanted to make writing rules as easy as possible.

So for anyone with that knowledge, it's clear that `dependencyRule`s are executed once per reference to that package in the tree, whereas `packageRule`s are executed once per unique package.

For vulnerabilities, it's enough to check once per unique package. So I'd personally perfer to stick to `vulnerabilityInPackageRule`.

2022-11-14 15:22 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +fun RuleSet.vulnerabilityInDependencyRule() = packageRule("VULNERABILITY_IN_DEPENDENCY") {
Looks like so, yes. That rule does not seems to make use of any of a dependency's / package reference's properties, i.e. it could (and should, for performance reasons) be a `packageRule` instead of a `dependencyRule`.

2022-11-14 16:14 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +fun RuleSet.vulnerabilityInDependencyRule() = packageRule("VULNERABILITY_IN_DEPENDENCY") {
Ok, I've dropped the commit from this PR. I'll make a follow-up PR for the package rule thing, as I still feel it may be a bit controversial.

2022-11-15 07:49 UTC, sschuberth approved these changes

2022-11-15 08:29 UTC, merged