evaluator.rules: Add handling for further license categories
oss-review-toolkit/ort-config pull request #77
Opened 2022-11-16 11:22 UTC by fviernau

See individual commits.

Context: #66.

2022-11-16 11:45 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +            "The dependency ${pkg.metadata.id.toCoordinates()} is licensed under the ScanCode 'commercial' " +
I realized too late that we're already doing this in other rules, but isn't it a bit risky to refer to ScanCode as a scanner here? This basically means users should not add commercial licenses from other scanners to the `license-classifications.yml`'s `commercial` category, which creates an unnecessary tight coupling to the contents of `evaluator.rules.kts`.

2022-11-16 11:45 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +).map { SpdxSingleLicenseExpression.parse(it) }.toSet()
Could use `mapTo`.

2022-11-16 11:45 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +val genericLicenses = getLicensesForCategory("generic")
On a related note, [ScanCode 31.0.1](https://github.com/nexB/scancode-toolkit/releases/tag/v31.0.1) introduced an `is_generic` flag in its output (see e.g. [here](https://scancode-licensedb.aboutcode.org/generic-cla.json) for `LicenseRef-scancode-generic-cla`). Maybe we should add support for such a flag in `LicenseFinding`, upgrade ScanCode (and the parser to populate that new field), and rely on that property instead of hard-coding license names.

2022-11-16 11:45 UTC, sschuberth commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +val unknownLicenses = getLicensesForCategory("unknown")
Similarly here, we could add support for ScanCode's `is_unknown` to our data model and handle unknown findings generically.

2022-11-16 12:51 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +            "The dependency ${pkg.metadata.id.toCoordinates()} is licensed under the ScanCode 'commercial' " +
I believe that for providing a real world example it suffices to use a single scanner, e.g. the de-facto default one in ORT. The license classifications YML is generated and the category 'commercial' refers to ScanCode's commercial category.

2022-11-16 12:52 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +).map { SpdxSingleLicenseExpression.parse(it) }.toSet()
I want to use an immutable set.

2022-11-16 12:53 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +val genericLicenses = getLicensesForCategory("generic")
This does rely on the is_generic flag already, see importer code.

2022-11-16 12:53 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +val unknownLicenses = getLicensesForCategory("unknown")
Similar to above.

2022-11-17 13:43 UTC, mnonnenmacher requested changes

2022-11-17 13:43 UTC, mnonnenmacher commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +            "The dependency ${pkg.metadata.id.toCoordinates()} is licensed under the ScanCode 'commercial' " +
IMO as long as classifications are generated from ScanCode it's good to mention it here as well to make clear where the classification is coming from.

2022-11-17 13:43 UTC, mnonnenmacher commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +// Set of licenses, which are not acted upon by the below policy rules.
I would appreciate if a short version of the explanation why these licenses are ignored from the commit message would also appear here, because this comment is what users will see.

2022-11-17 13:43 UTC, mnonnenmacher commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +val ignoredLicenses = listOf(
Why is this not the same as `genericLicenses`? After reading the commit message I would have expected that all generic licenses are ignored?

2022-11-17 13:43 UTC, mnonnenmacher commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +    "LicenseRef-scancode-see-license"
Similar to the question in the previous commit, what makes these unknown licenses special so that they shall be ignored but not others from the `unknownLicenses`?

2022-11-17 14:03 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +val ignoredLicenses = listOf(
The set of ignored licenses is currently a real subset of the union of 'generic' and 'unknown'.

It contains only some of the generic licenses which I believe should not be investigated.

2022-11-17 14:06 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +    "LicenseRef-scancode-see-license"
In my view it's waste of time to investigate these. 
Consider e.g. `LicenseRef-scancode-see-license` flags "See license in LICENSE".

How is that actionable? Create a curation which turns the detected license into NONE because the LICENSE file is scanned anyway? ...No, that's waste of time IMO and does add value.

2022-11-17 14:24 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +// Set of licenses, which are not acted upon by the below policy rules.
I've added a comment to each license ID.

2022-11-17 14:27 UTC, fviernau commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +    "LicenseRef-scancode-see-license"
I've removed 'free-unkown' from the list after looking again at it's triggers. 
Even though it flags on things like:  `license: "MIT"`

That gives quite a bit of things to investigate , as the effort is always limited, investigating 'free-unknow' may not be the best place to spend it. Anyhow, let's not ignore it for now.

2022-11-17 15:46 UTC, mnonnenmacher commented on evaluator-rules/src/main/resources/evaluator.rules.kts
> +val ignoredLicenses = listOf(
I wasn't obvious why a subset was chosen because the explanation sounds like it applies to generic licenses in general. With the added comments it's clearer.

2022-11-17 15:47 UTC, mnonnenmacher approved these changes

2022-11-17 15:48 UTC, tsteenbe approved these changes

2022-11-17 15:48 UTC, merged