deps(Gradle): Upgrade ORT to version e50456588d
oss-review-toolkit/ort-config pull request #99
Opened 2023-03-02 11:43 UTC by fviernau

A preceeding change renamed the notice template files, which was done to align with ORT's recent refactoring of the
`PlainTextTemplateReporter`, formerly called `NoticeTemplateReporter`.

Upgrade ORT to have this `PlainTextTemplateReporter` available.

2023-03-02 14:10 UTC, sschuberth commented
Looks like we should also migrate from `com.vdurmont:semver4j` to `org.semver4j:semver4j` here...

2023-03-02 17:34 UTC, tsteenbe approved these changes

2023-03-03 09:57 UTC, sschuberth requested changes

2023-03-03 09:57 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
> +                    if (version.isNotBlank()) {
Just throwing in some alternatives:
- `with(curation.id)` (even if it adds nesting)
- `curation.id.version.takeUnless { it.isBlank() }?.let { version ->`.

2023-03-03 09:57 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
> +                            issues += "The version '${version}' in file '$relativePath' is not a valid Ivy version " +
`{}` should now be dropped here.

2023-03-03 09:57 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
> +                                    "https://ant.apache.org/ivy/history/2.5.0/settings/version-matchers.html."
I guess the reason for using the `See:`-style was to *avoid* the need for a dot after the URL, which I know in some environments (like Azure pipelines log output) leads to invalid URLs as the dot it considered a literal part of the URL. Another way to avoid this would be to single-quote the URL. But actually, I'd prefer to stick to the `See:`-style in this case, as it's not part of the fix done in this commit anyway.

2023-03-03 09:57 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
> +    listOf(",", "~", "*", "+", ">", "<", "=", " - ", "^", ".x", "||").any { contains(it, ignoreCase = true) }
Missing final newline.

2023-03-03 10:08 UTC, fviernau commented on tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
> +                    if (version.isNotBlank()) {
I've kept this one as-is.

2023-03-03 10:21 UTC, sschuberth submitted a review, later dismissed
Approving despite my comments which could be addressed later.

2023-03-03 10:21 UTC, sschuberth commented on tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
> +    listOf(",", "~", "*", "+", ">", "<", "=", " - ", "^", ".x", "||").any { contains(it, ignoreCase = true) }
This recreates the list on each function call, which in this case is on each iteration over `curations`.

Generally, I wonder whether we shouldn't refactor the needed functionality in ORT to be public, and then make the `buildSrc` project depend on the necessary ORT artifact so we can reuse the code from ORT.

2023-03-03 10:31 UTC, fviernau commented on tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
> +    listOf(",", "~", "*", "+", ">", "<", "=", " - ", "^", ".x", "||").any { contains(it, ignoreCase = true) }
> This recreates the list on each function call,

I've fixed it.

2023-03-03 10:34 UTC, sschuberth approved these changes

2023-03-03 10:44 UTC, merged